// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4eWyxk77Eq4khyJXHnYKW3dyINSW2ypQ',
    appId: '1:211225225646:web:067522abafee8e2b7b403f',
    messagingSenderId: '211225225646',
    projectId: 'dyrou1-9274c',
    authDomain: 'dyrou1-9274c.firebaseapp.com',
    storageBucket: 'dyrou1-9274c.appspot.com',
    measurementId: 'G-CZJPMB4VY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgVmMBu5ku5B1u5Hf_9LXbLwDmjOkwaPo',
    appId: '1:211225225646:android:e679a014efa574cf7b403f',
    messagingSenderId: '211225225646',
    projectId: 'dyrou1-9274c',
    storageBucket: 'dyrou1-9274c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jR2CONE2-el17YmC7U1vOqi36dTtrc4',
    appId: '1:211225225646:ios:9bf18161ac7f335a7b403f',
    messagingSenderId: '211225225646',
    projectId: 'dyrou1-9274c',
    storageBucket: 'dyrou1-9274c.appspot.com',
    iosClientId: '211225225646-h9rc3ui00tup36sc9ge720j6onh4s3v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyRou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jR2CONE2-el17YmC7U1vOqi36dTtrc4',
    appId: '1:211225225646:ios:9bf18161ac7f335a7b403f',
    messagingSenderId: '211225225646',
    projectId: 'dyrou1-9274c',
    storageBucket: 'dyrou1-9274c.appspot.com',
    iosClientId: '211225225646-h9rc3ui00tup36sc9ge720j6onh4s3v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyRou',
  );
}
